import random
num = random.random()
numit1 = random.randint(1,60)
numit2 = random.randint(1,60)
numit3 = random.randint(1,60)
numit4 = random.randint(1,60)
numit5 = random.randint(1,60)
numit6 = random.randint(1,60)
print(num)
print('Sorteio Mega Sena{:=-^30}')
print(numit1, end=' ')
print(numit2, end=' ')
print(numit3, end=' ')
print(numit4, end=' ')
print(numit5, end=' ')
print(numit6)
print('-'*30)