frase = 'Curso em vídeo Python'
frase2 = frase.replace('Python','Teste')
print(frase[9::2])
print(len(frase))
print(frase.count('o',0,21))
print(frase.find('deo'))
print(frase.find('android'))
print('Curso' in frase)
print('Hoje' in frase)
print(frase)
print(frase2)
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.split())
print('-'.join(frase))