#Tabuada
a = int(input('Digite um número: '))
print('-'*20)
print('{} x {} = {}'.format(a, 1, a*1))
#print('{} x 1 = '.format(a), end='')
#print(a*1)
print('{} x 2 = '.format(a), end='')
print(a*2)
print('{} x 3 = '.format(a), end='')
print(a*3)
print('{} x 4 = '.format(a), end='')
print(a*4)
print('{} x 5 = '.format(a), end='')
print(a*5)
print('{} x 6 = '.format(a), end='')
print(a*6)
print('{} x 7 = '.format(a), end='')
print(a*7)
print('{} x 8 = '.format(a), end='')
print(a*8)
print('{} x 9 = '.format(a), end='')
print(a*9)
print('{} x 10 = '.format(a), end='')
print(a*10)
print('-'*20)


